### ISSUE TITLE
Requiring flux from npm

### ISSUE THREAD

**Issue by ptomasroos** [zertosh/ssr-demo-kit#3]
Whats the reason for not using https://www.npmjs.org/package/flux?

var Dispatcher = require('path/to/this/directory/Flux').Dispatcher;

**Comment by zertosh** [comment]
5 months later... Because the `invariant` that it uses skips the message check. But for simplicity, I just added it back in https://github.com/zertosh/ssr-demo-kit/pull/6.

The actual dispatcher that we use is [here](https://gist.github.com/zertosh/35731ff6a86aac55e0e3). It's the same as the Flux repo one, except that it uses React's `invariant` and doesn't include error messages in production builds.
