### ISSUE TITLE
Removal of Action Source

### ISSUE THREAD

**Issue by Kingdutch** [zertosh/ssr-demo-kit#7]
#6 closed #3 but 2950444c1a784c38917cd6bd5331cd69f5b3e447 also removed AppDispatcher's support for Action sources. Is there a reasoning for this?

It seemed like a useful feature or does it go against isomorphic ideas as it shouldn't matter where an action came from? I realize you probably have better things to do than update this repo, but it's a great source of information Perhaps git's commit body could be used for the reasoning on such changes to clarify your thought process to those less enlightened : )

**Comment by zertosh** [comment]
Action sources were part of Facebook's original stock Flux implementation - so we followed it. We never really used them - and neither did Facebook - I can't remember if there was a post about it or not.

For us, it turned out to be clearer to have the source embedded into the action name (if needed), or to tack on an "origin" or "source" prop on the action itself from within the action creator. For example, all AJAX incoming actions are named "RECEIVE_XXX" and they typically have an error counterpart named "RECEIVE_XXX_ERROR".

**Comment by Kingdutch** [comment]
Makes sense : )
